# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f20a28321f0025462761161d19456758504c4200abcd9cb86064747e0009ad85345abbb23937c2accc22b19dafa08a9c0a7888c2354917c5cbe0a0c4557d1bf

test:
  secret_key_base: dacd401aed1967d347832555dc9e2791c6641440ae4172b2b3e71f93915fb3ed6d28801e9396cd98244abf5fd8f2d3a7159d5e131c73f172fdc3bdbad617c526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
